//KIC-DCSAI-242-F-006
//KIC-DCSAI-242-F-038
//KIC-DCSAI-242-F-040
//KIC-DCSAI-242-F-049
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalcourseworkpkg;

import javax.swing.JOptionPane;

/**
 *
 * @author isula
 */
public class VehicleSelection extends javax.swing.JFrame {

    /**
     * Creates new form VehicleSelection
     */
    public VehicleSelection() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pnlVehicle02 = new javax.swing.JPanel();
        lblVehicle02 = new javax.swing.JLabel();
        lblNameVehiicle02 = new javax.swing.JLabel();
        lblInfoVehiicle02 = new javax.swing.JLabel();
        btnBookNowVehicle02 = new javax.swing.JButton();
        pnlVehicle03 = new javax.swing.JPanel();
        lblVehicle03 = new javax.swing.JLabel();
        lblNameVehiicle03 = new javax.swing.JLabel();
        lblInfoVehiicle03 = new javax.swing.JLabel();
        btnBookNowVehicle03 = new javax.swing.JButton();
        pnlVehicle04 = new javax.swing.JPanel();
        lblVehicle04 = new javax.swing.JLabel();
        lblNameVehiicle04 = new javax.swing.JLabel();
        lblInfoVehiicle04 = new javax.swing.JLabel();
        btnBookNowVehicle04 = new javax.swing.JButton();
        pnlVehicle01 = new javax.swing.JPanel();
        lblVehicle2 = new javax.swing.JLabel();
        lblNameVehiicle01 = new javax.swing.JLabel();
        lblInfoVehiicle01 = new javax.swing.JLabel();
        btnBookNowVehicle01 = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgpkg/logo 119 x 56.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Discover Unforgettable");
        jLabel4.setToolTipText("");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel4.setFocusable(false);
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("The ultimate retreat for your body, Travel Comfortable");
        jLabel5.setToolTipText("");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel5.setFocusable(false);
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        pnlVehicle02.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        pnlVehicle02.setPreferredSize(new java.awt.Dimension(290, 140));

        lblVehicle02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVehicle02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgpkg/car 122 x 124.png"))); // NOI18N

        lblNameVehiicle02.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNameVehiicle02.setText("Car");

        lblInfoVehiicle02.setText("Price for One Day ");

        btnBookNowVehicle02.setText("BookNow");
        btnBookNowVehicle02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookNowVehicle02ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlVehicle02Layout = new javax.swing.GroupLayout(pnlVehicle02);
        pnlVehicle02.setLayout(pnlVehicle02Layout);
        pnlVehicle02Layout.setHorizontalGroup(
            pnlVehicle02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVehicle02Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVehicle02, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlVehicle02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVehicle02Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlVehicle02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNameVehiicle02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblInfoVehiicle02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlVehicle02Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBookNowVehicle02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(286, 286, 286))
        );
        pnlVehicle02Layout.setVerticalGroup(
            pnlVehicle02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVehicle02Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlVehicle02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVehicle02Layout.createSequentialGroup()
                        .addComponent(lblNameVehiicle02, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblInfoVehiicle02, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBookNowVehicle02))
                    .addComponent(lblVehicle02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlVehicle03.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        pnlVehicle03.setPreferredSize(new java.awt.Dimension(290, 140));

        lblVehicle03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVehicle03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgpkg/van 122 x 124.png"))); // NOI18N

        lblNameVehiicle03.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNameVehiicle03.setText("Van");

        lblInfoVehiicle03.setText("Price for One Day ");

        btnBookNowVehicle03.setText("BookNow");
        btnBookNowVehicle03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookNowVehicle03ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlVehicle03Layout = new javax.swing.GroupLayout(pnlVehicle03);
        pnlVehicle03.setLayout(pnlVehicle03Layout);
        pnlVehicle03Layout.setHorizontalGroup(
            pnlVehicle03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVehicle03Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVehicle03, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlVehicle03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVehicle03Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlVehicle03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNameVehiicle03, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(lblInfoVehiicle03, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVehicle03Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBookNowVehicle03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlVehicle03Layout.setVerticalGroup(
            pnlVehicle03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVehicle03Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlVehicle03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVehicle03Layout.createSequentialGroup()
                        .addComponent(lblNameVehiicle03, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblInfoVehiicle03, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBookNowVehicle03))
                    .addComponent(lblVehicle03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlVehicle04.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        pnlVehicle04.setPreferredSize(new java.awt.Dimension(290, 140));

        lblVehicle04.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVehicle04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgpkg/cab 122 x 124.png"))); // NOI18N

        lblNameVehiicle04.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNameVehiicle04.setText("Jeep");

        lblInfoVehiicle04.setText("Price for One Day ");

        btnBookNowVehicle04.setText("BookNow");
        btnBookNowVehicle04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookNowVehicle04ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlVehicle04Layout = new javax.swing.GroupLayout(pnlVehicle04);
        pnlVehicle04.setLayout(pnlVehicle04Layout);
        pnlVehicle04Layout.setHorizontalGroup(
            pnlVehicle04Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVehicle04Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVehicle04, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlVehicle04Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVehicle04Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlVehicle04Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNameVehiicle04, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(lblInfoVehiicle04, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVehicle04Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBookNowVehicle04, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlVehicle04Layout.setVerticalGroup(
            pnlVehicle04Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVehicle04Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlVehicle04Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVehicle04Layout.createSequentialGroup()
                        .addComponent(lblNameVehiicle04, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblInfoVehiicle04, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBookNowVehicle04))
                    .addComponent(lblVehicle04, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlVehicle01.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        pnlVehicle01.setPreferredSize(new java.awt.Dimension(290, 140));

        lblVehicle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVehicle2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgpkg/bike 122 x 124.png"))); // NOI18N

        lblNameVehiicle01.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNameVehiicle01.setText("Bike");

        lblInfoVehiicle01.setText("Price for One Day ");

        btnBookNowVehicle01.setText("BookNow");
        btnBookNowVehicle01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookNowVehicle01ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlVehicle01Layout = new javax.swing.GroupLayout(pnlVehicle01);
        pnlVehicle01.setLayout(pnlVehicle01Layout);
        pnlVehicle01Layout.setHorizontalGroup(
            pnlVehicle01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVehicle01Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVehicle2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlVehicle01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNameVehiicle01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblInfoVehiicle01, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(btnBookNowVehicle01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlVehicle01Layout.setVerticalGroup(
            pnlVehicle01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVehicle01Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlVehicle01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVehicle2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlVehicle01Layout.createSequentialGroup()
                        .addComponent(lblNameVehiicle01, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblInfoVehiicle01, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBookNowVehicle01)))
                .addContainerGap())
        );

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlVehicle01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlVehicle02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(btnHome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(pnlVehicle03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlVehicle04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnHome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlVehicle02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlVehicle01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlVehicle03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlVehicle04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        if (!LoginManager.getInstance().isLoggedIn()) {
            HomePage obj01 = new HomePage();
            obj01.setVisible(true);
            dispose();
            return;
        }
        HomePageLoggedIn obj01 = new HomePageLoggedIn();
        obj01.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnBookNowVehicle01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookNowVehicle01ActionPerformed
        if (!LoginManager.getInstance().isLoggedIn()) {
            JOptionPane.showMessageDialog(null, "Please log in first.", "Access Denied", JOptionPane.ERROR_MESSAGE);
            return;
        }

        CostCalculationVehicle01 obj01 = new CostCalculationVehicle01();
        obj01.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBookNowVehicle01ActionPerformed

    private void btnBookNowVehicle02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookNowVehicle02ActionPerformed
        if (!LoginManager.getInstance().isLoggedIn()) {
            JOptionPane.showMessageDialog(null, "Please log in first.", "Access Denied", JOptionPane.ERROR_MESSAGE);
            return;
        }

        CostCalculationVehicle02 obj01 = new CostCalculationVehicle02();
        obj01.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBookNowVehicle02ActionPerformed

    private void btnBookNowVehicle03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookNowVehicle03ActionPerformed
        if (!LoginManager.getInstance().isLoggedIn()) {
            JOptionPane.showMessageDialog(null, "Please log in first.", "Access Denied", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        CostCalculationVehicle03 obj01 = new CostCalculationVehicle03();
        obj01.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBookNowVehicle03ActionPerformed

    private void btnBookNowVehicle04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookNowVehicle04ActionPerformed
        if (!LoginManager.getInstance().isLoggedIn()) {
            JOptionPane.showMessageDialog(null, "Please log in first.", "Access Denied", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        CostCalculationVehicle04 obj01 = new CostCalculationVehicle04();
        obj01.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBookNowVehicle04ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VehicleSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VehicleSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VehicleSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VehicleSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VehicleSelection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBookNowVehicle01;
    private javax.swing.JButton btnBookNowVehicle02;
    private javax.swing.JButton btnBookNowVehicle03;
    private javax.swing.JButton btnBookNowVehicle04;
    private javax.swing.JButton btnHome;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblInfoVehiicle01;
    private javax.swing.JLabel lblInfoVehiicle02;
    private javax.swing.JLabel lblInfoVehiicle03;
    private javax.swing.JLabel lblInfoVehiicle04;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNameVehiicle01;
    private javax.swing.JLabel lblNameVehiicle02;
    private javax.swing.JLabel lblNameVehiicle03;
    private javax.swing.JLabel lblNameVehiicle04;
    private javax.swing.JLabel lblVehicle02;
    private javax.swing.JLabel lblVehicle03;
    private javax.swing.JLabel lblVehicle04;
    private javax.swing.JLabel lblVehicle2;
    private javax.swing.JPanel pnlVehicle01;
    private javax.swing.JPanel pnlVehicle02;
    private javax.swing.JPanel pnlVehicle03;
    private javax.swing.JPanel pnlVehicle04;
    // End of variables declaration//GEN-END:variables
}
